### PR TITLE
changed readme

### PR DESCRIPTION
**Pull request by rjpepmeyer**
made changes to readme file for onboarding

### CODE REVIEW

**Comment by kddrake** [comment]
Just use your repo's title (ronald-pepmeyer-ux-iop)... no need to include a 'title' header

**Comment by jakekemple** [comment]
:+1:

**Comment by rginther** [comment]
:+1:

**Comment by rjpepmeyer** [comment]
Thanks for pointing that out; I've pushed that change to repo-setup

**Pull request merged**
